### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by fahussain** [casbin/casbin-vscode-plugin#4]
I don't see this in the vscode market place. How can I install this?

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by noaryan** [comment]
@fahussain If you have Node installed you can use `vsce` to package the extension and install it.

`git clone https://github.com/casbin/casbin-vscode-plugin.git`
`npm install -g vsce`
`cd casbin-vscode-plugin`
`vsce package`
`code --install-extension casbin-0.0.1.vsix`

**Comment by nomeguy** [comment]
@fahussain see: https://marketplace.visualstudio.com/items?itemName=Casbin.vscode-casbin
